# replace NAME with your project name

name: deploy backend
on:
  push:
    paths:
      - backend/**/*
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary

      - name: Adding Known Hosts
        run: ssh-keyscan -p ${{ secrets.SSH_PORT }} -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy with rsync
        run: ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "mkdir -p /var/app/NAME" && rsync -avz --delete -e "ssh -p ${{ secrets.SSH_PORT }}" ./backend ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/app/NAME

      - name: Restart Docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker build -t rescode/NAME:v0.0.1 /var/app/NAME && \
            docker stop NAME || true && \
            docker rm NAME || true && \
            docker run \
            -p 5543:5543 \
            -e PRODUCTION=true \
            -e PORT="5543" \
            -e VARIABLE="${{ secrets.VARIABLE }}" \
            --log-driver json-file --log-opt max-size=10m --log-opt max-file=3 \
            --name=NAME -it -d --restart unless-stopped rescode/NAME:v0.0.1
